depositor: "depositor@example.com"
# authorities
projects: 'tt44pm84n'
journals: ""
subjects: ""
current_organisations: 'm900nt40f'
current_people: 'vd66vz88c'
qualification_names: ""
departments: '1c18df763'
