depositor: "depositor@example.com"
# authorities
projects: '3x816m604'
journals: ""
subjects: ""
current_organisations: '1z40ks800'
current_persons: 'v979v304g'
qualification_names: ""
departments: 'j3860692c'
