depositor: "depositor@example.com"
# authorities
projects: 'pv63g024f'
journals: ""
subjects: ""
current_organisations: '7s75dc36z'
current_people: 'd504rk32w'
qualification_names: ""
departments: 'qr46r0806'
