depositor: "depositor@example.com"
# authorities
projects: '4f16c281g'
current_organisations: '5712m6524'
current_people: '7w62f8209'
departments: 'nz805z68q'
projects: '4f16c281g'
current_organisations: '5712m6524'
current_people: '7w62f8209'
departments: 'nz805z68q'
