# authorities
subjects: ""
projects: '5q47rn72z'
organisations: 'vh53wv72q'
places: ""
people: 'zs25x844t'
groups: ""
departments: '3197xm05t'
projects: '5q47rn72z'
current_organisations: 'vh53wv72q'
people: 'zs25x844t'
departments: '3197xm05t'
projects: '5q47rn72z'
current_organisations: 'vh53wv72q'
people: 'zs25x844t'
departments: '3197xm05t'
