depositor: "depositor@example.com"
# authorities
projects: '9593tv123'
current_organisations: 'j67313767'
current_people: 'p5547r367'
departments: '4m90dv48q'
projects: '9593tv123'
current_organisations: 'j67313767'
current_people: 'p5547r367'
departments: '4m90dv48q'
