# Generated by local:models:install
class FileSet < ActiveFedora::Base
  include ::Hyrax::FileSetBehavior

  # already has title, rights, and more

  property :content_version, predicate: ::RDF::Vocab::SCHEMA.version,
           multiple: true do |index|
    index.as :stored_searchable, :facetable
  end

end
